#!/bin/bash

cd ~
ln -si ~/vimrc/.vimrc ~/.vimrc

if [ -d ~/.vim/bundle/vundle ]; then
  cd ~/vimrc
  git pull origin master
  cd -
else
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

vim -u ~/vimrc/bundles.vim +BundleInstall +qa
