#!/bin/bash

cd ~
ln -si ~/vimrc/.vimrc ~/.vimrc

if [ -d ~/.vim/bundle/neobundle.vim ]; then
  cd ~/vimrc
  git pull origin master
  cd -
else
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
fi

vim
